apiVersion: v1
kind: PersistentVolume
metadata:
  name: jsmith-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/jsmith-pv-1
---    
apiVersion: v1
kind: Namespace
metadata:
  name: jsmith
  namespace: jsmith
